apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: project-azure-yaml
spec:
  compositeTypeRef:
    apiVersion: my.platform.io/v1alpha1
    kind: Project
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: rg-dev
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-dev"

          - name: rg-stg
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-stg"

          - name: rg-prod
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-prod"