apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  forProvider:
    location: norwayeast
  providerConfigRef:
    name: default
    kind: ProviderConfig