apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system