apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-providers
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/providers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-providers
  interval: 1m
  path: ./infrastructure/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system